version: '3.8'

services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - /opt/docker/alist/config:/opt/alist/data
      - /opt:/mnt
    ports:
      - 5244:5244
    restart: unless-stopped
