version: '3.8'

services:
  autobrr:
    image: ghcr.io/autobrr/autobrr:latest
    container_name: autobrr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - /opt/docker/autobrr/config:/config
      - /opt/downloads:/downloads
    ports:
      - 7474:7474
    restart: unless-stopped
