# 脚本名称: bazarr.yml
# 脚本描述: Bazarr字幕自动化管理工具的Docker Compose配置
# 脚本路径: https://raw.githubusercontent.com/everett7623/PTtools/main/config/docker-compose/bazarr.yml
# 使用方法: docker-compose -f bazarr.yml up -d
# 作者: Jensfrank
# 更新时间: 2025-06-29

version: '3.8'

services:
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    volumes:
      - /opt/docker/bazarr/config:/config
      - /opt/docker/radarr/movies:/movies
      - /opt/docker/sonarr/tv:/tv
    ports:
      - "6767:6767"
    networks:
      - pttools

networks:
  pttools:
    driver: bridge
    name: pttools
