# 脚本名称: calibre-web.yml
# 脚本描述: Calibre-Web电子书管理工具的Docker Compose配置
# 脚本路径: https://raw.githubusercontent.com/everett7623/PTtools/main/config/docker-compose/calibre-web.yml
# 使用方法: docker-compose -f calibre-web.yml up -d
# 作者: Jensfrank
# 更新时间: 2025-06-29

version: '3.8'

services:
  calibre-web:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - /opt/docker/calibre-web/config:/config
      - /opt/docker/calibre-web/books:/books
    ports:
      - "8083:8083"
    networks:
      - pttools

networks:
  pttools:
    driver: bridge
    name: pttools
