# 脚本名称: homepage.yml
# 脚本描述: Homepage个人主页面板的Docker Compose配置
# 脚本路径: https://raw.githubusercontent.com/everett7623/PTtools/main/config/docker-compose/homepage.yml
# 使用方法: docker-compose -f homepage.yml up -d
# 作者: Jensfrank
# 更新时间: 2025-06-29

version: '3.8'

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    volumes:
      - /opt/docker/homepage/config:/app/config
      - /opt/docker:/opt/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "3004:3000"
    networks:
      - pttools

networks:
  pttools:
    driver: bridge
    name: pttools
