# IYUUPlus Docker Compose配置文件
# 脚本名称: iyuuplus.yml
# 脚本描述: IYUUPlus自动辅种工具的Docker Compose配置
# 脚本路径: https://raw.githubusercontent.com/everett7623/PTtools/main/config/docker-compose/iyuuplus.yml
# 使用方法: docker-compose -f iyuuplus.yml up -d
# 作者: everett7623
# 更新时间: 2025-06-25

version: '3.8'

services:
  iyuuplus:
    image: iyuucn/iyuuplus-dev:latest
    container_name: iyuuplus
    stdin_open: true
    tty: true
    volumes:
      - /opt/docker/iyuuplus/iyuu:/iyuu
      - /opt/docker/iyuuplus/data:/data
      - /opt/docker/qbittorrent/config/qBittorrent/BT_backup:/qb
      - /opt/docker/transmission/config/torrents:/tr
    ports:
      - 8780:8780
    restart: always
