version: '3.8'

services:
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - AUTO_UPDATE=true
    volumes:
      - /opt/docker/jackett/config:/config
      - /opt/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
