# 脚本名称: jellyfin.yml
# 脚本描述: Jellyfin开源媒体服务器的Docker Compose配置
# 脚本路径: https://raw.githubusercontent.com/everett7623/PTtools/main/config/docker-compose/jellyfin.yml
# 使用方法: docker-compose -f jellyfin.yml up -d
# 作者: Jensfrank
# 更新时间: 2025-06-29

version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - JELLYFIN_PublishedServerUrl=http://localhost:8097
    volumes:
      - /opt/docker/jellyfin/config:/config
      - /opt/docker/jellyfin/cache:/cache
      - /opt/docker/jellyfin/media:/media
      - /opt/docker/radarr/movies:/movies
      - /opt/docker/sonarr/tv:/tv
      - /opt/docker/lidarr/music:/music
    ports:
      - "8097:8096"
    devices:
      - /dev/dri:/dev/dri
    networks:
      - pttools

networks:
  pttools:
    driver: bridge
    name: pttools
