# 脚本名称: lucky.yml
# 脚本描述: Lucky DDNS和反向代理工具的Docker Compose配置
# 脚本路径: https://raw.githubusercontent.com/everett7623/PTtools/main/config/docker-compose/lucky.yml
# 使用方法: docker-compose -f lucky.yml up -d
# 作者: Jensfrank
# 更新时间: 2025-06-29

version: '3.8'

services:
  lucky:
    image: gdy666/lucky:latest
    container_name: lucky
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    volumes:
      - /opt/docker/lucky/config:/goodluck
      - /opt/docker/lucky/data:/data
    ports:
      - "16601:16601"
      - "16666:16666"
    networks:
      - pttools

networks:
  pttools:
    driver: bridge
    name: pttools
