# 脚本名称: metatube.yml
# 脚本描述: MetaTube视频元数据管理工具的Docker Compose配置
# 脚本路径: https://raw.githubusercontent.com/everett7623/PTtools/main/config/docker-compose/metatube.yml
# 使用方法: docker-compose -f metatube.yml up -d
# 作者: Jensfrank
# 更新时间: 2025-06-29

version: '3.8'

services:
  metatube:
    image: metatube/metatube:latest
    container_name: metatube
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    volumes:
      - /opt/docker/metatube/config:/config
      - /opt/docker/metatube/data:/data
      - /opt/docker/metatube/media:/media
    ports:
      - "8200:8200"
    networks:
      - pttools

networks:
  pttools:
    driver: bridge
    name: pttools
