# MoviePilot Docker Compose配置文件
# 脚本名称: moviepilot.yml
# 脚本描述: MoviePilot自动化影视库管理工具的Docker Compose配置
# 脚本路径: https://raw.githubusercontent.com/everett7623/PTtools/main/configs/docker-compose/moviepilot.yml
# 使用方法: docker-compose -f moviepilot.yml up -d
# 作者: everett7623
# 更新时间: 2025-06-25

version: '3.8'

services:
  moviepilot:
    image: jxxghp/moviepilot-v2:latest
    stdin_open: true
    tty: true
    container_name: moviepilot-v2
    hostname: moviepilot-v2
    network_mode: host
    volumes:
      - /opt/downloads:/media
      - /opt/docker/moviepilot/config:/config
      - /opt/docker/moviepilot/core:/moviepilot/.cache/ms-playwright
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/docker/qbittorrent/config/qBittorrent/BT_backup:/qb
      - /opt/docker/transmission/config/torrents:/tr
    environment:
      - NGINX_PORT=3000
      - PORT=3001
      - PUID=0
      - PGID=0
      - UMASK=000
      - TZ=Asia/Shanghai
      - SUPERUSER=admin
    restart: always
