# 脚本名称: ombi.yml
# 脚本描述: Ombi媒体请求管理工具的Docker Compose配置
# 脚本路径: https://raw.githubusercontent.com/everett7623/PTtools/main/config/docker-compose/ombi.yml
# 使用方法: docker-compose -f ombi.yml up -d
# 作者: Jensfrank
# 更新时间: 2025-06-29

version: '3.8'

services:
  ombi:
    image: linuxserver/ombi:latest
    container_name: ombi
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    volumes:
      - /opt/docker/ombi/config:/config
    ports:
      - "3579:3579"
    networks:
      - pttools

networks:
  pttools:
    driver: bridge
    name: pttools
