# 脚本名称: organizr.yml
# 脚本描述: Organizr服务整合面板的Docker Compose配置
# 脚本路径: https://raw.githubusercontent.com/everett7623/PTtools/main/config/docker-compose/organizr.yml
# 使用方法: docker-compose -f organizr.yml up -d
# 作者: Jensfrank
# 更新时间: 2025-06-29

version: '3.8'

services:
  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    volumes:
      - /opt/docker/organizr/config:/config
    ports:
      - "9983:80"
    networks:
      - pttools

networks:
  pttools:
    driver: bridge
    name: pttools
