# 脚本名称: plex.yml
# 脚本描述: Plex媒体服务器的Docker Compose配置
# 脚本路径: https://raw.githubusercontent.com/everett7623/PTtools/main/config/docker-compose/plex.yml
# 使用方法: docker-compose -f plex.yml up -d
# 作者: Jensfrank
# 更新时间: 2025-06-29

version: '3.8'

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=
    volumes:
      - /opt/docker/plex/config:/config
      - /opt/docker/plex/transcode:/transcode
      - /opt/docker/plex/media:/media
      - /opt/docker/radarr/movies:/movies
      - /opt/docker/sonarr/tv:/tv
      - /opt/docker/lidarr/music:/music
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    devices:
      - /dev/dri:/dev/dri
    networks:
      - pttools

networks:
  pttools:
    driver: bridge
    name: pttools
