version: '3.8'

services:
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - /opt/docker/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
