# qBittorrent Docker Compose配置文件
# 脚本名称: qbittorrent.yml
# 脚本描述: qBittorrent应用的Docker Compose配置
# 脚本路径: https://raw.githubusercontent.com/everett7623/PTtools/main/config/docker-compose/qbittorrent.yml
# 使用方法: docker-compose -f qbittorrent.yml up -d
# 作者: everett7623
# 更新时间: 2025-06-25

version: '3.8'

services:
  qbittorrent:
    image: linuxserver/qbittorrent:4.6.7
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
    volumes:
      - /opt/docker/qbittorrent/config:/config
      - /opt/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
