# 脚本名称: qiandao.yml
# 脚本描述: Qiandao自动签到工具的Docker Compose配置
# 脚本路径: https://raw.githubusercontent.com/everett7623/PTtools/main/config/docker-compose/qiandao.yml
# 使用方法: docker-compose -f qiandao.yml up -d
# 作者: Jensfrank
# 更新时间: 2025-06-29

version: '3.8'

services:
  qiandao:
    image: qdtoday/qd:latest
    container_name: qiandao
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    volumes:
      - /opt/docker/qiandao/config:/usr/src/app/config
      - /opt/docker/qiandao/data:/usr/src/app/data
    ports:
      - "8923:80"
    networks:
      - pttools

networks:
  pttools:
    driver: bridge
    name: pttools
