# 脚本名称: sonarr.yml
# 脚本描述: Sonarr电视剧自动化管理工具的Docker Compose配置
# 脚本路径: https://raw.githubusercontent.com/everett7623/PTtools/main/config/docker-compose/sonarr.yml
# 使用方法: docker-compose -f sonarr.yml up -d
# 作者: Jensfrank
# 更新时间: 2025-06-29

version: '3.8'

services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    volumes:
      - /opt/docker/sonarr/config:/config
      - /opt/downloads:/downloads
      - /opt/docker/sonarr/tv:/tv
    ports:
      - "8989:8989"
    networks:
      - pttools

networks:
  pttools:
    driver: bridge
    name: pttools
