version: '3.8'

services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - /opt/docker/sonarr/config:/config
      - /opt/downloads:/downloads
      - /opt/downloads:/tv
    ports:
      - 8989:8989
    restart: unless-stopped
