# 脚本名称: transmission.yml
# 脚本描述: Transmission 4.0.5 BT下载客户端的Docker Compose配置
# 脚本路径: https://raw.githubusercontent.com/everett7623/PTtools/main/config/docker-compose/transmission.yml
# 使用方法: docker-compose -f transmission.yml up -d
# 作者: Jensfrank
# 更新时间: 2025-06-29

version: '3.8'

services:
  transmission:
    image: linuxserver/transmission:4.0.5
    container_name: transmission
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
      - USER=admin
      - PASS=admin123
    volumes:
      - /opt/docker/transmission/config:/config
      - /opt/downloads:/downloads
      - /opt/downloads/watch:/watch
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    networks:
      - pttools

networks:
  pttools:
    driver: bridge
    name: pttools
