services:
  transmission:
    image: linuxserver/transmission:4.0.5
    container_name: transmission
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - TRANSMISSION_WEB_HOME=/config/webui/trguing
      - USER=admin
      - PASS=adminadmin
    volumes:
      - /opt/docker/transmission/config:/config
      - /opt/downloads:/downloads
      - /opt/docker/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - pt-network

networks:
  pt-network:
    driver: bridge
